@startuml zuma

class Jugador
class Proyectil
class Esfera
class Arena
class Mapa
class Carril
class Mira
class Base
class Vida


//usa
Jugador o-- Proyectil
Jugador o-- Mapa
Jugador o-- Base
Jugador o-- Vida
Esfera o-- Carril
Jugador o-- Mira

//tiene
Jugador *-- Proyectil
Jugador *-- Mira
Jugador *-- Vida
Jugador *-- Base
Esfera *-- Carril
Esfera *-- Mapa


//es
Jugador--|>





@enduml